<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PDICommon\PDICommon.csproj" />
    <ProjectReference Include="..\PDIDatabase\PDIDatabase.csproj" />
    <ProjectReference Include="..\PDIEntities\PDIEntities.csproj" />
  </ItemGroup>

</Project>
